// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: protobuf/proto/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloseReason int32

const (
	CloseReason_CLOSE_REASON_UNSPECIFIED CloseReason = 0
	CloseReason_CLOSE                    CloseReason = 1
	CloseReason_SELF_DESTRUCT            CloseReason = 2
	CloseReason_SHUTDOWN                 CloseReason = 3
)

// Enum value maps for CloseReason.
var (
	CloseReason_name = map[int32]string{
		0: "CLOSE_REASON_UNSPECIFIED",
		1: "CLOSE",
		2: "SELF_DESTRUCT",
		3: "SHUTDOWN",
	}
	CloseReason_value = map[string]int32{
		"CLOSE_REASON_UNSPECIFIED": 0,
		"CLOSE":                    1,
		"SELF_DESTRUCT":            2,
		"SHUTDOWN":                 3,
	}
)

func (x CloseReason) Enum() *CloseReason {
	p := new(CloseReason)
	*p = x
	return p
}

func (x CloseReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloseReason) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_agent_proto_enumTypes[0].Descriptor()
}

func (CloseReason) Type() protoreflect.EnumType {
	return &file_protobuf_proto_agent_proto_enumTypes[0]
}

func (x CloseReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloseReason.Descriptor instead.
func (CloseReason) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{0}
}

type ContainerOperation int32

const (
	ContainerOperation_CONTAINER_OPERATION_UNSPECIFIED ContainerOperation = 0
	ContainerOperation_START_CONTAINER                 ContainerOperation = 1
	ContainerOperation_STOP_CONTAINER                  ContainerOperation = 2
	ContainerOperation_RESTART_CONTAINER               ContainerOperation = 3
)

// Enum value maps for ContainerOperation.
var (
	ContainerOperation_name = map[int32]string{
		0: "CONTAINER_OPERATION_UNSPECIFIED",
		1: "START_CONTAINER",
		2: "STOP_CONTAINER",
		3: "RESTART_CONTAINER",
	}
	ContainerOperation_value = map[string]int32{
		"CONTAINER_OPERATION_UNSPECIFIED": 0,
		"START_CONTAINER":                 1,
		"STOP_CONTAINER":                  2,
		"RESTART_CONTAINER":               3,
	}
)

func (x ContainerOperation) Enum() *ContainerOperation {
	p := new(ContainerOperation)
	*p = x
	return p
}

func (x ContainerOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_agent_proto_enumTypes[1].Descriptor()
}

func (ContainerOperation) Type() protoreflect.EnumType {
	return &file_protobuf_proto_agent_proto_enumTypes[1]
}

func (x ContainerOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerOperation.Descriptor instead.
func (ContainerOperation) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{1}
}

type ContainerState int32

const (
	ContainerState_CONTAINER_STATE_UNSPECIFIED ContainerState = 0
	ContainerState_RUNNING                     ContainerState = 1
	ContainerState_WAITING                     ContainerState = 2
	ContainerState_EXITED                      ContainerState = 3
	ContainerState_REMOVED                     ContainerState = 4
)

// Enum value maps for ContainerState.
var (
	ContainerState_name = map[int32]string{
		0: "CONTAINER_STATE_UNSPECIFIED",
		1: "RUNNING",
		2: "WAITING",
		3: "EXITED",
		4: "REMOVED",
	}
	ContainerState_value = map[string]int32{
		"CONTAINER_STATE_UNSPECIFIED": 0,
		"RUNNING":                     1,
		"WAITING":                     2,
		"EXITED":                      3,
		"REMOVED":                     4,
	}
)

func (x ContainerState) Enum() *ContainerState {
	p := new(ContainerState)
	*p = x
	return p
}

func (x ContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_agent_proto_enumTypes[2].Descriptor()
}

func (ContainerState) Type() protoreflect.EnumType {
	return &file_protobuf_proto_agent_proto_enumTypes[2]
}

func (x ContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState.Descriptor instead.
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{2}
}

//
// Common
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{0}
}

//
// Agent commands
type AgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AgentCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*AgentCommand_ContainerState
	//	*AgentCommand_Close
	//	*AgentCommand_ContainerCommand
	//	*AgentCommand_ContainerDelete
	//	*AgentCommand_ContainerLog
	//	*AgentCommand_ContainerInspect
	Command isAgentCommand_Command `protobuf_oneof:"command"`
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (m *AgentCommand) GetCommand() isAgentCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *AgentCommand) GetContainerState() *ContainerStateRequest {
	if x, ok := x.GetCommand().(*AgentCommand_ContainerState); ok {
		return x.ContainerState
	}
	return nil
}

func (x *AgentCommand) GetClose() *CloseConnectionRequest {
	if x, ok := x.GetCommand().(*AgentCommand_Close); ok {
		return x.Close
	}
	return nil
}

func (x *AgentCommand) GetContainerCommand() *ContainerCommandRequest {
	if x, ok := x.GetCommand().(*AgentCommand_ContainerCommand); ok {
		return x.ContainerCommand
	}
	return nil
}

func (x *AgentCommand) GetContainerDelete() *ContainerDeleteRequest {
	if x, ok := x.GetCommand().(*AgentCommand_ContainerDelete); ok {
		return x.ContainerDelete
	}
	return nil
}

func (x *AgentCommand) GetContainerLog() *ContainerLogRequest {
	if x, ok := x.GetCommand().(*AgentCommand_ContainerLog); ok {
		return x.ContainerLog
	}
	return nil
}

func (x *AgentCommand) GetContainerInspect() *ContainerInspectRequest {
	if x, ok := x.GetCommand().(*AgentCommand_ContainerInspect); ok {
		return x.ContainerInspect
	}
	return nil
}

type isAgentCommand_Command interface {
	isAgentCommand_Command()
}

type AgentCommand_ContainerState struct {
	ContainerState *ContainerStateRequest `protobuf:"bytes,1,opt,name=containerState,proto3,oneof"`
}

type AgentCommand_Close struct {
	Close *CloseConnectionRequest `protobuf:"bytes,2,opt,name=close,proto3,oneof"`
}

type AgentCommand_ContainerCommand struct {
	ContainerCommand *ContainerCommandRequest `protobuf:"bytes,3,opt,name=containerCommand,proto3,oneof"`
}

type AgentCommand_ContainerDelete struct {
	ContainerDelete *ContainerDeleteRequest `protobuf:"bytes,4,opt,name=containerDelete,proto3,oneof"`
}

type AgentCommand_ContainerLog struct {
	ContainerLog *ContainerLogRequest `protobuf:"bytes,5,opt,name=containerLog,proto3,oneof"`
}

type AgentCommand_ContainerInspect struct {
	ContainerInspect *ContainerInspectRequest `protobuf:"bytes,6,opt,name=containerInspect,proto3,oneof"`
}

func (*AgentCommand_ContainerState) isAgentCommand_Command() {}

func (*AgentCommand_Close) isAgentCommand_Command() {}

func (*AgentCommand_ContainerCommand) isAgentCommand_Command() {}

func (*AgentCommand_ContainerDelete) isAgentCommand_Command() {}

func (*AgentCommand_ContainerLog) isAgentCommand_Command() {}

func (*AgentCommand_ContainerInspect) isAgentCommand_Command() {}

type ContainerStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OneShot *bool `protobuf:"varint,1,opt,name=oneShot,proto3,oneof" json:"oneShot,omitempty"`
}

func (x *ContainerStateRequest) Reset() {
	*x = ContainerStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStateRequest) ProtoMessage() {}

func (x *ContainerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStateRequest.ProtoReflect.Descriptor instead.
func (*ContainerStateRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerStateRequest) GetOneShot() bool {
	if x != nil && x.OneShot != nil {
		return *x.OneShot
	}
	return false
}

type CloseConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason CloseReason `protobuf:"varint,1,opt,name=reason,proto3,enum=agent.CloseReason" json:"reason,omitempty"`
}

func (x *CloseConnectionRequest) Reset() {
	*x = CloseConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnectionRequest) ProtoMessage() {}

func (x *CloseConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnectionRequest.ProtoReflect.Descriptor instead.
func (*CloseConnectionRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CloseConnectionRequest) GetReason() CloseReason {
	if x != nil {
		return x.Reason
	}
	return CloseReason_CLOSE_REASON_UNSPECIFIED
}

type ContainerCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Operation ContainerOperation `protobuf:"varint,2,opt,name=operation,proto3,enum=agent.ContainerOperation" json:"operation,omitempty"`
}

func (x *ContainerCommandRequest) Reset() {
	*x = ContainerCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCommandRequest) ProtoMessage() {}

func (x *ContainerCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCommandRequest.ProtoReflect.Descriptor instead.
func (*ContainerCommandRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerCommandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerCommandRequest) GetOperation() ContainerOperation {
	if x != nil {
		return x.Operation
	}
	return ContainerOperation_CONTAINER_OPERATION_UNSPECIFIED
}

type ContainerDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ContainerDeleteRequest) Reset() {
	*x = ContainerDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDeleteRequest) ProtoMessage() {}

func (x *ContainerDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDeleteRequest.ProtoReflect.Descriptor instead.
func (*ContainerDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContainerLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Streaming bool   `protobuf:"varint,2,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Tail      uint32 `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`
}

func (x *ContainerLogRequest) Reset() {
	*x = ContainerLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogRequest) ProtoMessage() {}

func (x *ContainerLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogRequest.ProtoReflect.Descriptor instead.
func (*ContainerLogRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerLogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerLogRequest) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *ContainerLogRequest) GetTail() uint32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type ContainerInspectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ContainerInspectRequest) Reset() {
	*x = ContainerInspectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerInspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInspectRequest) ProtoMessage() {}

func (x *ContainerInspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInspectRequest.ProtoReflect.Descriptor instead.
func (*ContainerInspectRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerInspectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContainerStateItemPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Internal int32 `protobuf:"varint,1,opt,name=internal,proto3" json:"internal,omitempty"`
	External int32 `protobuf:"varint,2,opt,name=external,proto3" json:"external,omitempty"`
}

func (x *ContainerStateItemPort) Reset() {
	*x = ContainerStateItemPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerStateItemPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStateItemPort) ProtoMessage() {}

func (x *ContainerStateItemPort) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStateItemPort.ProtoReflect.Descriptor instead.
func (*ContainerStateItemPort) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ContainerStateItemPort) GetInternal() int32 {
	if x != nil {
		return x.Internal
	}
	return 0
}

func (x *ContainerStateItemPort) GetExternal() int32 {
	if x != nil {
		return x.External
	}
	return 0
}

type ContainerStateItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command   string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// The 'State' of the container (Created, Running, etc)
	State ContainerState `protobuf:"varint,4,opt,name=state,proto3,enum=agent.ContainerState" json:"state,omitempty"`
	// The 'reason' behind 'state'.
	Reason    string                    `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ImageName string                    `protobuf:"bytes,6,opt,name=imageName,proto3" json:"imageName,omitempty"`
	ImageTag  string                    `protobuf:"bytes,7,opt,name=imageTag,proto3" json:"imageTag,omitempty"`
	Ports     []*ContainerStateItemPort `protobuf:"bytes,8,rep,name=ports,proto3" json:"ports,omitempty"`
}

func (x *ContainerStateItem) Reset() {
	*x = ContainerStateItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerStateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStateItem) ProtoMessage() {}

func (x *ContainerStateItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStateItem.ProtoReflect.Descriptor instead.
func (*ContainerStateItem) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerStateItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerStateItem) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ContainerStateItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ContainerStateItem) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CONTAINER_STATE_UNSPECIFIED
}

func (x *ContainerStateItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ContainerStateItem) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ContainerStateItem) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *ContainerStateItem) GetPorts() []*ContainerStateItemPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ContainerStateListMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ContainerStateItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ContainerStateListMessage) Reset() {
	*x = ContainerStateListMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerStateListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStateListMessage) ProtoMessage() {}

func (x *ContainerStateListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStateListMessage.ProtoReflect.Descriptor instead.
func (*ContainerStateListMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ContainerStateListMessage) GetData() []*ContainerStateItem {
	if x != nil {
		return x.Data
	}
	return nil
}

//
// Container log
type ContainerLogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log string `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *ContainerLogMessage) Reset() {
	*x = ContainerLogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerLogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogMessage) ProtoMessage() {}

func (x *ContainerLogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogMessage.ProtoReflect.Descriptor instead.
func (*ContainerLogMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ContainerLogMessage) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

//
// Container inspect
type ContainerInspectMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inspection string `protobuf:"bytes,2,opt,name=inspection,proto3" json:"inspection,omitempty"`
}

func (x *ContainerInspectMessage) Reset() {
	*x = ContainerInspectMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerInspectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInspectMessage) ProtoMessage() {}

func (x *ContainerInspectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInspectMessage.ProtoReflect.Descriptor instead.
func (*ContainerInspectMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ContainerInspectMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInspectMessage) GetInspection() string {
	if x != nil {
		return x.Inspection
	}
	return ""
}

var File_protobuf_proto_agent_proto protoreflect.FileDescriptor

var file_protobuf_proto_agent_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x35, 0x0a,
	0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0xc1, 0x03, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x46, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a,
	0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x49, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x40, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x12,
	0x4c, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x10, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x42, 0x09, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x42, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x07, 0x6f, 0x6e, 0x65, 0x53, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x6e, 0x65, 0x53, 0x68, 0x6f, 0x74, 0x88, 0x01, 0x01,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x6e, 0x65, 0x53, 0x68, 0x6f, 0x74, 0x22, 0x44, 0x0a, 0x16,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x37, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x16, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x2d, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x49, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0xb0, 0x02, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x54, 0x61, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x54, 0x61, 0x67, 0x12, 0x33, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f,
	0x72, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x4a, 0x0a, 0x19, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0x4d,
	0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x57, 0x0a,
	0x0b, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x18,
	0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c,
	0x4f, 0x53, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x45, 0x4c, 0x46, 0x5f, 0x44, 0x45,
	0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x48, 0x55, 0x54,
	0x44, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x2a, 0x79, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x1f,
	0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41,
	0x49, 0x4e, 0x45, 0x52, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x43,
	0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x10,
	0x03, 0x2a, 0x64, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x45, 0x58, 0x49, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45,
	0x4d, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x04, 0x32, 0xbd, 0x02, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x12, 0x32, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x10, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x13,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x30, 0x01, 0x12, 0x42, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x12, 0x3e, 0x0a, 0x0f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x12, 0x1a, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x28, 0x01, 0x12, 0x40, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x49, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x12, 0x1e, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x79, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x69,
	0x6f, 0x2f, 0x64, 0x61, 0x72, 0x6b, 0x6c, 0x65, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proto_agent_proto_rawDescOnce sync.Once
	file_protobuf_proto_agent_proto_rawDescData = file_protobuf_proto_agent_proto_rawDesc
)

func file_protobuf_proto_agent_proto_rawDescGZIP() []byte {
	file_protobuf_proto_agent_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_agent_proto_rawDescData)
	})
	return file_protobuf_proto_agent_proto_rawDescData
}

var file_protobuf_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protobuf_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protobuf_proto_agent_proto_goTypes = []interface{}{
	(CloseReason)(0),                  // 0: agent.CloseReason
	(ContainerOperation)(0),           // 1: agent.ContainerOperation
	(ContainerState)(0),               // 2: agent.ContainerState
	(*Empty)(nil),                     // 3: agent.Empty
	(*AgentInfo)(nil),                 // 4: agent.AgentInfo
	(*AgentCommand)(nil),              // 5: agent.AgentCommand
	(*ContainerStateRequest)(nil),     // 6: agent.ContainerStateRequest
	(*CloseConnectionRequest)(nil),    // 7: agent.CloseConnectionRequest
	(*ContainerCommandRequest)(nil),   // 8: agent.ContainerCommandRequest
	(*ContainerDeleteRequest)(nil),    // 9: agent.ContainerDeleteRequest
	(*ContainerLogRequest)(nil),       // 10: agent.ContainerLogRequest
	(*ContainerInspectRequest)(nil),   // 11: agent.ContainerInspectRequest
	(*ContainerStateItemPort)(nil),    // 12: agent.ContainerStateItemPort
	(*ContainerStateItem)(nil),        // 13: agent.ContainerStateItem
	(*ContainerStateListMessage)(nil), // 14: agent.ContainerStateListMessage
	(*ContainerLogMessage)(nil),       // 15: agent.ContainerLogMessage
	(*ContainerInspectMessage)(nil),   // 16: agent.ContainerInspectMessage
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
}
var file_protobuf_proto_agent_proto_depIdxs = []int32{
	6,  // 0: agent.AgentCommand.containerState:type_name -> agent.ContainerStateRequest
	7,  // 1: agent.AgentCommand.close:type_name -> agent.CloseConnectionRequest
	8,  // 2: agent.AgentCommand.containerCommand:type_name -> agent.ContainerCommandRequest
	9,  // 3: agent.AgentCommand.containerDelete:type_name -> agent.ContainerDeleteRequest
	10, // 4: agent.AgentCommand.containerLog:type_name -> agent.ContainerLogRequest
	11, // 5: agent.AgentCommand.containerInspect:type_name -> agent.ContainerInspectRequest
	0,  // 6: agent.CloseConnectionRequest.reason:type_name -> agent.CloseReason
	1,  // 7: agent.ContainerCommandRequest.operation:type_name -> agent.ContainerOperation
	17, // 8: agent.ContainerStateItem.createdAt:type_name -> google.protobuf.Timestamp
	2,  // 9: agent.ContainerStateItem.state:type_name -> agent.ContainerState
	12, // 10: agent.ContainerStateItem.ports:type_name -> agent.ContainerStateItemPort
	13, // 11: agent.ContainerStateListMessage.data:type_name -> agent.ContainerStateItem
	4,  // 12: agent.Agent.Connect:input_type -> agent.AgentInfo
	14, // 13: agent.Agent.ContainerState:input_type -> agent.ContainerStateListMessage
	9,  // 14: agent.Agent.DeleteContainer:input_type -> agent.ContainerDeleteRequest
	15, // 15: agent.Agent.ContainerLog:input_type -> agent.ContainerLogMessage
	16, // 16: agent.Agent.ContainerInspect:input_type -> agent.ContainerInspectMessage
	5,  // 17: agent.Agent.Connect:output_type -> agent.AgentCommand
	3,  // 18: agent.Agent.ContainerState:output_type -> agent.Empty
	3,  // 19: agent.Agent.DeleteContainer:output_type -> agent.Empty
	3,  // 20: agent.Agent.ContainerLog:output_type -> agent.Empty
	3,  // 21: agent.Agent.ContainerInspect:output_type -> agent.Empty
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_protobuf_proto_agent_proto_init() }
func file_protobuf_proto_agent_proto_init() {
	if File_protobuf_proto_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerInspectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerStateItemPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerStateItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerStateListMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerLogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerInspectMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_proto_agent_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*AgentCommand_ContainerState)(nil),
		(*AgentCommand_Close)(nil),
		(*AgentCommand_ContainerCommand)(nil),
		(*AgentCommand_ContainerDelete)(nil),
		(*AgentCommand_ContainerLog)(nil),
		(*AgentCommand_ContainerInspect)(nil),
	}
	file_protobuf_proto_agent_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_agent_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_proto_agent_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_agent_proto_depIdxs,
		EnumInfos:         file_protobuf_proto_agent_proto_enumTypes,
		MessageInfos:      file_protobuf_proto_agent_proto_msgTypes,
	}.Build()
	File_protobuf_proto_agent_proto = out.File
	file_protobuf_proto_agent_proto_rawDesc = nil
	file_protobuf_proto_agent_proto_goTypes = nil
	file_protobuf_proto_agent_proto_depIdxs = nil
}
