name: product_builder
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    types: [edited, opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: read
  packages: read
env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: dyrector-io/darklens
  BUILD_WORKING_DIRECTORY: web
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  crux_build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    container:
      image: ghcr.io/dyrector-io/dyrectorio/builder-images/nodejs:1
    defaults:
      run:
        working-directory: ${{ env.BUILD_WORKING_DIRECTORY }}
    environment: Workflow - Protected
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # fixes: fatal: unsafe repository
      - name: Adding workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Docker build
      # latest tag for now
        run: docker build -t ${GITHUB_REGISTRY}/${IMAGE_NAME}:latest .
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Push
        run: docker push -a ${GITHUB_REGISTRY}/${IMAGE_NAME}
